[theme]
name = "nord"

[palette]
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"
nord7 = "#8fbcbb"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
nord10 = "#5e81ac"
nord11 = "#bf616a"
nord12 = "#d08770"
nord13 = "#ebcb8b"
nord14 = "#a3be8c"
nord15 = "#b48ead"

[colors]
Background = "nord1"
Foreground = "nord6"
Highlight = "nord9"
HighlightInactive = "nord3"
Selection = "nord9"
Prompt = "nord9"
PromptSuccess = "nord14"
PromptError = "nord11"
Hint = "nord3"

[style]
AlertError = "nord11"
AlertSuccess = "nord14"
AlertInfo = "nord9"
AlertWarning = "nord13"
AlertCustom = "nord7"
