name: Shellcheck

on:
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          echo "Running shellcheck on scripts..."
          # find shell scripts and run shellcheck; exit non-zero on issues
          find . -type f -name "*.sh" -print0 | xargs -0 shellcheck -f gcc
